### ISSUE TITLE
Enable Branch Protection, switch semantic-release-bot to seambot

### ISSUE THREAD

**Issue by seveibar** [seamapi/seamapi-types#59]
semantic-release-bot wasn't able to commit to this repo because of branch protection rules, and I can't add a rule to allow it to bypass them. We need to use seambot to commit to this repo instead of semantic-release-bot for branch protection to work.

CC @razor-x @codetheweb unless you guys know a better way

![image](https://user-images.githubusercontent.com/1910070/235540482-027badcb-20da-4d60-97c4-40fd5c8c7e4c.png)

**Comment by codetheweb** [comment]
whoops I just turned on branch protection for this repo

yeah I think seambot is the right solution
